

data:
  base_path: data/
  ground_truth: ground_truth.nc
  reconstructions:
    base_path: data/predictions/
    plain:
      full: full_pred_plain.npy
      loo: loo_pred_plain.nc
    arm:
      full: full_pred_arm.npy
      loo: loo_pred_arm.nc
    arm_wt:
      full: full_pred_arm_wt.npy
      loo: loo_pred_arm_wt.nc
  metadata:
    station_indices: todo